apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: job-scheduler
  labels:
    app.kubernetes.io/name: job-scheduler
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
